
export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
        <h1 className={styles.title}>
          Starting new app with <a href="https://nextjs.org">Next.js!</a>
        </h1>
      </main>
    </div>
  )
}
